const seed = {
  passengers: [
    { id: "p1", name: "Arun Shah", age: 34, gender: "Male", berth: "Lower berth", meal: "Vegetarian" },
    { id: "p2", name: "Meera Shah", age: 31, gender: "Female", berth: "Lower berth", meal: "Vegetarian" }
  ],
  journeys: [{ id: "j1", date: "2026-09-23", train: "12951", from: "Mumbai Central", to: "New Delhi", class: "2A", quota: "General", passengerIds: ["p1", "p2"], waitlist: false, createdAt: "2026-09-16" }]
};
const storeKey = "railready-data-v1";
let data = JSON.parse(localStorage.getItem(storeKey) || "null") || seed;
let activeReviewId = null;
const $ = (s) => document.querySelector(s);
const save = () => localStorage.setItem(storeKey, JSON.stringify(data));
const formatDate = (date) => new Intl.DateTimeFormat("en-IN", { day: "numeric", month: "short", year: "numeric" }).format(new Date(`${date}T00:00:00`));
const daysUntil = (date) => Math.max(0, Math.ceil((new Date(`${date}T00:00:00`) - new Date()) / 86400000));
const readiness = (j) => { const missing = [j.date, j.train, j.from, j.to, j.class, j.quota].filter(Boolean).length < 6 || !j.passengerIds.length; return missing ? 0 : 100; };
const bookingMessage = (j) => { const days = daysUntil(j.date); return days === 0 ? "Journey today" : days === 1 ? "Journey tomorrow" : `${days} days to journey`; };

function renderNav() { $("#passengerCount").textContent = data.passengers.length; $("#journeyCount").textContent = data.journeys.length; }
function planCard(j) { const names = j.passengerIds.map(id => data.passengers.find(p => p.id === id)?.name).filter(Boolean); const readinessValue = readiness(j); return `<article class="plan-card"><div class="plan-card-head"><span class="date-badge"><strong>${new Date(`${j.date}T00:00:00`).getDate()}</strong>${new Intl.DateTimeFormat("en", {month:"short"}).format(new Date(`${j.date}T00:00:00`))}</span><span class="status ${readinessValue === 100 ? "ready" : "needs"}">${readinessValue === 100 ? "Ready to review" : "Needs details"}</span></div><p class="train-no">TRAIN ${j.train} · ${j.class} · ${j.quota}</p><h3>${j.from} <span>→</span> ${j.to}</h3><p class="passenger-line">${names.join(" · ") || "No passengers yet"}</p><div class="plan-card-footer"><span>${bookingMessage(j)}</span><button class="review-button" data-review="${j.id}">Review plan →</button></div></article>`; }
function renderDashboard() { const plans = [...data.journeys].sort((a,b) => a.date.localeCompare(b.date)); $("#upcomingPlans").innerHTML = plans.length ? plans.slice(0,3).map(planCard).join("") : `<div class="empty-state"><h3>No journeys planned yet</h3><p>Save your travellers, then set up your first booking-ready plan.</p><button class="primary-button" data-open-journey>Plan a journey</button></div>`; $("#metricPassengers").textContent = data.passengers.length; $("#metricReady").textContent = data.journeys.filter(j => readiness(j) === 100).length; const next = plans[0]; $("#metricReminder").textContent = next ? formatDate(next.date) : "—"; }
function renderPassengers() { $("#passengerList").innerHTML = data.passengers.length ? data.passengers.map(p => `<article class="passenger-card"><div class="passenger-initial">${p.name.split(" ").map(n=>n[0]).slice(0,2).join("")}</div><div><h3>${p.name}</h3><p>${p.age} years · ${p.gender}</p></div><div class="preferences"><span>${p.berth}</span><span>${p.meal}</span></div><button class="delete-button" data-delete-passenger="${p.id}" aria-label="Delete ${p.name}">×</button></article>`).join("") : `<div class="empty-state"><h3>Your traveller list is empty</h3><p>Add a passenger profile to reuse their details in journey plans.</p><button class="primary-button" id="emptyAddPassenger">Add passenger</button></div>`; }
function renderJourneys() { $("#journeyList").innerHTML = data.journeys.length ? [...data.journeys].sort((a,b)=>a.date.localeCompare(b.date)).map(j => `<article class="journey-row"><div class="journey-date"><strong>${new Date(`${j.date}T00:00:00`).getDate()}</strong><span>${new Intl.DateTimeFormat("en", {month:"short"}).format(new Date(`${j.date}T00:00:00`))}</span></div><div class="journey-main"><p class="train-no">TRAIN ${j.train} · ${j.class}</p><h3>${j.from} <span>→</span> ${j.to}</h3><p>${j.passengerIds.length} passenger${j.passengerIds.length === 1 ? "" : "s"} · ${j.quota} quota · ${j.waitlist ? "RAC/waitlist allowed" : "Confirmed preference"}</p></div><div class="readiness"><strong>${readiness(j)}%</strong><span>Ready</span><i><b style="width:${readiness(j)}%"></b></i></div><button class="review-button" data-review="${j.id}">Review →</button></article>`).join("") : `<div class="empty-state"><h3>No booking plans yet</h3><p>Start with a date, train number, route, and the travellers joining you.</p><button class="primary-button" data-open-journey>Plan a journey</button></div>`; }
function renderAll() { renderNav(); renderDashboard(); renderPassengers(); renderJourneys(); }
function showToast(message) { const toast = $("#toast"); toast.textContent = message; toast.classList.add("show"); setTimeout(()=>toast.classList.remove("show"), 3200); }
function openPassenger() { $("#passengerForm").reset(); $("#passengerDialog").showModal(); }
function openJourney() { if (!data.passengers.length) { showToast("Add a passenger profile before creating a plan."); openPassenger(); return; } $("#journeyForm").reset(); $("#journeyForm [name=date]").min = new Date().toISOString().slice(0,10); $("#passengerPicker").innerHTML = data.passengers.map((p,i)=>`<label class="person-check"><input type="checkbox" name="passenger" value="${p.id}" ${i === 0 ? "checked" : ""}/><span><strong>${p.name}</strong><small>${p.age} yrs · ${p.berth}</small></span></label>`).join(""); $("#journeyDialog").showModal(); }
function review(id) { const j = data.journeys.find(item => item.id === id); if (!j) return; activeReviewId = id; const people = j.passengerIds.map(id => data.passengers.find(p=>p.id===id)).filter(Boolean); $("#reviewTitle").textContent = `${j.from} to ${j.to}`; $("#reviewContent").innerHTML = `<div class="review-route"><span>${formatDate(j.date)}</span><h3>${j.from} <b>→</b> ${j.to}</h3><p>Train ${j.train} · ${j.class} · ${j.quota} quota</p></div><div class="review-details"><div><span>PASSENGERS</span>${people.map(p=>`<p><strong>${p.name}</strong> · ${p.age} yrs · ${p.berth} · ${p.meal}</p>`).join("")}</div><div><span>BOOKING PREFERENCE</span><p>${j.waitlist ? "RAC / waitlist may be considered" : "Prefer confirmed accommodation"}</p></div></div>`; $("#reviewDialog").showModal(); }

document.addEventListener("click", (event) => { const nav = event.target.closest(".nav-link"); if(nav){ event.preventDefault(); document.querySelectorAll(".nav-link").forEach(l=>l.classList.remove("active")); nav.classList.add("active"); document.querySelectorAll(".page").forEach(p=>p.classList.remove("active-page")); $(nav.getAttribute("href")).classList.add("active-page"); } if(event.target.closest("[data-open-journey]")) openJourney(); if(event.target.closest("#addPassenger, #emptyAddPassenger")) openPassenger(); const reviewBtn=event.target.closest("[data-review]"); if(reviewBtn) review(reviewBtn.dataset.review); const del=event.target.closest("[data-delete-passenger]"); if(del){ const used=data.journeys.some(j=>j.passengerIds.includes(del.dataset.deletePassenger)); if(used) return showToast("This passenger is used in a journey plan. Remove the plan first."); data.passengers=data.passengers.filter(p=>p.id!==del.dataset.deletePassenger); save(); renderAll(); } });
$("#passengerForm").addEventListener("submit", event => { event.preventDefault(); const f = new FormData(event.target); data.passengers.push({ id: crypto.randomUUID(), name:f.get("name").trim(), age:Number(f.get("age")), gender:f.get("gender"), berth:f.get("berth"), meal:f.get("meal") }); save(); $("#passengerDialog").close(); renderAll(); showToast("Passenger saved securely on this device."); });
$("#journeyForm").addEventListener("submit", event => { event.preventDefault(); const f=new FormData(event.target); const ids=f.getAll("passenger"); if(!ids.length) return showToast("Select at least one passenger."); data.journeys.push({ id:crypto.randomUUID(), date:f.get("date"), train:f.get("train").trim(), from:f.get("from").trim(), to:f.get("to").trim(), class:f.get("class"), quota:f.get("quota"), passengerIds:ids, waitlist:f.get("waitlist") === "on", createdAt:new Date().toISOString().slice(0,10) }); save(); $("#journeyDialog").close(); renderAll(); showToast("Journey plan saved. Your details are ready to review."); });
$("#closeReview").onclick = () => $("#reviewDialog").close(); $("#reviewBack").onclick = () => $("#reviewDialog").close(); $("#handoff").onclick = () => { $("#reviewDialog").close(); showToast("Open IRCTC in a new tab to complete sign-in and payment yourself."); window.open("https://www.irctc.co.in/nget/train-search", "_blank", "noopener,noreferrer"); };
$("#resetData").onclick = () => { data = structuredClone(seed); save(); renderAll(); showToast("Demo data restored."); };
renderAll();
